### ISSUE TITLE
Automatyczne generowanie OG w Canva

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#10]
Research czy da się zautomatyzować tworzenie grafik dla OG z szablonów w canva poprzez API

**Comment by KamilWiecek** [comment]
@kaluzaaa  Co to jest OG?

**Comment by kaluzaaa** [comment]
@kwiecek open graph image czyli ten obrazek, który pokazuje Ci się jak robisz share na fb,ln twitter i innych.

Samo zadanie to, czy da się to dynamicznie generować z canva (skopiować już gotowy obraz, zmienić tekst, pobrać).

**Comment by kamil-mrzyglod** [comment]
@kaluzaaa - jeśli nikt nie wziął jeszcze tego na klatę to możesz na mnie przypiąć taska.

**Comment by kamil-mrzyglod** [comment]
Canva nie ma takiego API - taka funkcjonalność jest na poziomie feature request, czekam na ich odpowiedź czy mają jakieś ETA.

A może alternatywa typu https://github.com/vercel/og-image - czyli zrób to sam?

Ewentualnie - https://www.bannerbear.com/?

EDIT: ETA dla takowego API to połowa 2021 więc nope, raczej trzeba kombinować z czymś innym ;)

**Comment by kaluzaaa** [comment]
@kamil-mrzyglod zainspirowałeś! Jest thum.io, który za free udostępnia generowanie png ze screenshotów -> https://image.thum.io/get/ogImage/https://azurecommunity.pl/blog/azure-solutions-architect-qa-aad-part2
