### ISSUE TITLE
Generowanie og-image dla postów

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#16]
Generujemy za pomocą thum.io #10
Generowanie odbywa się za pomocą podania przygotowanego url. Przykład działającego https://image.thum.io/get/ogImage/https://azurecommunity.pl/blog/azure-solutions-architect-qa-aad-part2

Do zrobienia:

- [x] Automatyczne kopiowanie plików (postów) z `_post` do` _og-images` w Github Actions (`.github/workflows/test.yml`) przed krokiem `helaili/jekyll-action@2.0.4`
- [ ] Przerobinie szablonu `_layouts/og-image.html`, żeby to wygądało ;-) Powinno się mieścić dynamicznie od 1-4 do autorów (imię, naziwsko, avatar) i tytuł postu. thum.io robi screnshot w rozdzielczości 1200x630 i pod taką trzeba robić szablon.

Do testów przekopiowac sobie z pliki z `_post` do` _og-images`. Strony generują się z prefixem `og-image` zamiast `blog`, czyli http://localhost:4000/og-image/azure-solutions-architect-qa-aad-part2

**Comment by aryll** [comment]
Czy mamy jakąś bazę (chodzi mi głównie o ten obrazek bo jest trochę jak logo grupy)
![image](https://user-images.githubusercontent.com/5950108/102819472-cf4ca800-43d3-11eb-87fc-cfa324a96c4c.png)

**Comment by kaluzaaa** [comment]
@aryll może coś takiego lekkiego w stopce i tylko drobne logo w rogu.

![image](https://user-images.githubusercontent.com/4700951/102821795-fdcc8200-43d7-11eb-8ad6-9e438561bc1e.png)
![image](https://user-images.githubusercontent.com/4700951/102821886-38361f00-43d8-11eb-921b-a2c749376148.png)
![image](https://user-images.githubusercontent.com/4700951/102821909-42581d80-43d8-11eb-84a5-6ab6887af1f7.png)

@eklime zrób może jakąś paczkę i tu wrzuć

**Comment by kaluzaaa** [comment]
Kopiowanie dodane do Actions

**Comment by kaluzaaa** [comment]
![image](https://user-images.githubusercontent.com/4700951/103169415-b876dd00-483b-11eb-87e7-83ed9a6b7930.png)

tak wyglądają na dev.to

**Comment by kaluzaaa** [comment]
i jeszcze inne
![Uploading image.png…]()

**Comment by aryll** [comment]
image.thum.io zżera sporo css'ów robiąc printscreena... Wyszło mi coś takiego:
![image](https://user-images.githubusercontent.com/5950108/103226718-0f101400-492d-11eb-8f77-0bff09ce63e2.png)

Od razu odpowiadam na pytania:
- wszystkie style żeby zrobić avatar w kółku mi odrzuciło (może ktoś chciałby u siebie spróbować jakąś magię?)
- nazwiska nie chcą się wycentrować obok obrazka
- background można zmienić tylko trzeba wiedzieć na jaki 😄 - ja nic ciekawszego nie znalazłam

Uwagi, sugestie, pomysły?
@kaluzaaa @eklime @maciejgos @kmadof ?

A tutaj jest do tego draftowy PR: https://github.com/AzureCommunityPL/azurecommunitypl.github.io/pull/19
