### ISSUE TITLE
Przygotowanie mapy/grafa strony

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#31]
i dorzucenie do https://github.com/AzureCommunityPL/azurecommunitypl.github.io/blob/master/docs/new_design.md

**Comment by kmadof** [comment]
Wezmę jeszcze to :)

**Comment by kmadof** [comment]
Usiadłem nad tematem i na chwile obecną mam coś takiego:
![image](https://user-images.githubusercontent.com/1680172/104267307-a2028f80-5491-11eb-9318-3fdeabeb9ec0.png)

Dorzuciłem stronkę `Kontakt`  - bo zwyczajnie jest to dość oczekiwana strona, jakby ktoś chciał się skontaktować. Zastanawiam się też o stronie `O nas`. Teraz pytanie czy tutaj zaczynamy dyskusję czy dorzucić do new_design i czekamy na spotkanie.
