### ISSUE TITLE
Co powinna zawierać "Główna strona"?

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#32]
i dorzucenie do https://github.com/AzureCommunityPL/azurecommunitypl.github.io/blob/master/docs/new_design.md

**Comment by maciejgos** [comment]
@kaluzaaa przypisz do mnie

**Comment by maciejgos** [comment]
Do przegadania propozycja:
- Krótkie info o community (kim jesteśmy), moze być na tle banner-u
- Najblizsze wydarzenia (2-3, reszta na stronie z listą wydarzeń)
- Najnowsze wpisy na blog
- Sponsorzy

**Comment by kaluzaaa** [comment]
- miejsce pod hero/lead do promowania 3 rzeczy (blog, cfp, wydarzenie)

**Comment by maciejgos** [comment]
Dorzuciłem zmiany w commit https://github.com/AzureCommunityPL/azurecommunitypl.github.io/pull/30/commits/5e73d174d8033e249f3fd14b1a32e6b42c8e6cc7
Wszystko jest w PR https://github.com/AzureCommunityPL/azurecommunitypl.github.io/pull/30

**Comment by kmadof** [comment]
- link do `Discussions` na GitHub
