### ISSUE TITLE
Co powinna zawierać "Jak publikować"?

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#33]
i dorzucenie do https://github.com/AzureCommunityPL/azurecommunitypl.github.io/blob/master/docs/new_design.md

**Comment by kmadof** [comment]
@kaluzaaa przypisz to do mnie jak możesz - plissss :D

**Comment by kmadof** [comment]
- instrukcja jak lokalnie skonfigurować stronę - jako opcja może skrypt do tego gdzie wykorzystamy github cli żeby zrobić forka
- wymagania formalne co do publikowanej treści
