### ISSUE TITLE
Co powinna zawierać "Strona autora"?

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#35]
i dorzucenie do https://github.com/AzureCommunityPL/azurecommunitypl.github.io/blob/master/docs/new_design.md

**Comment by kmadof** [comment]
- bio/about me
- name
- github profile
- linked in profile
- twitter profile
- facebook profile
- website link
- image url
- wpisy autora

**Comment by kmadof** [comment]
Może wpisy autora na osi czasu, jak to jest na przykład na SO w story
![image](https://user-images.githubusercontent.com/1680172/104377031-20a90c80-5526-11eb-8e18-15ee84e76672.png)
