### ISSUE TITLE
Co powinna zawierać strona z postem?

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#36]
i dorzucenie do https://github.com/AzureCommunityPL/azurecommunitypl.github.io/blob/master/docs/new_design.md

**Comment by kaluzaaa** [comment]
Obsługa wszystkich styli z konwersji z markdown -> https://themes.gohugo.io/theme/axiom/post/markdown-syntax/

**Comment by kaluzaaa** [comment]
- Komentarze
  Opcje:
  - https://utteranc.es/
  - Disqus (trochę róźnych uwag lata w kierunku tego rozwiązania)
  - Prosty JS na bazie tego? - https://aristath.github.io/blog/static-site-comments-using-github-issues-api

**Comment by kmadof** [comment]
Co jest z `Disqus` nie tak. Ja nie słyszałem narzekań, ale też nie szukałem ich specjalnie.
