### ISSUE TITLE
Co powinna zawierać "Lista wydarzeń"?

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#38]
i dorzucenie do https://github.com/AzureCommunityPL/azurecommunitypl.github.io/blob/master/docs/new_design.md

**Comment by aryll** [comment]
1) lista wydarzeń
- myślę że mniej-więc w takiej podobnej formie jak tu (obstawiam, że nie będziemy mieli więcej niż 3-5 wydarzeń w miesiącu (https://nil.org.pl/lista-wydarzen?year=2021&month=1&week=53&day=null&active_page=1&by=month -> dałabym tylko miesiące bez konkretnych dni na górnej listwie)
- informacje na wydarzeniu: data, tytuł, autor/autorzy (może w formie awatarów) , poziom - kilknięcie przenosiłoby do postu z większą ilością informacji
- filtrowanie (miesiąc/rok, online/stacjonarnie, autor, tag, poziom)

2) instrukcja jak dodać wydarzenie
3) informacje kto może publikować wydarzenia, na jakich warunkach i gdzie są publikowane (FB, GitHub, Meetup itp)
