### ISSUE TITLE
Co powinna zawierać "Lista autorów"?

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#39]
i dorzucenie do https://github.com/AzureCommunityPL/azurecommunitypl.github.io/blob/master/docs/new_design.md

**Comment by kmadof** [comment]
Lista autorów w zasadniczej częsci pokrywałaby się ze stroną o autorze w takim sensie że każda wizytówka zawierałaby (prawie) te same informacje co strona dla pojedynczego autora:

- bio/about me
- name
- github profile
- linked in profile
- twitter profile
- facebook profile
- website link
- image url

A ponadto może jakieś małe ikonaki w stylu
- organizator
- uczestnik
- i do tego jakieś country dla wpisów/ wystąpień/ uczestnictwa w hackatonach
