### ISSUE TITLE
Jak powinien wyglądać one-pager pod eventy?

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#40]
i dorzucenie do https://github.com/AzureCommunityPL/azurecommunitypl.github.io/blob/master/docs/new_design.md

**Comment by kamil-mrzyglod** [comment]
Bazując na szablonie:

- tytuł wydarzenia
- data / venue
- one liner z opisem
- link / button do kupna biletów / rejestracji
- dłuższy opis wydarzenia
- organizatorzy
- sponsorzy
- regulamin
- code of conduct
- privacy policy
- harmonogram wydarzenia

Opcjonalne elementy:

- wrzutka z poprzednich edycji
- lista speakerów(jeśli to event typu meetup / konferencja)
- box z biletami(jeśli wydarzenie płatne)
- social linki do wydarzenia
- nagrody(w kontekście np. hackathonu)
- opis venue
