### ISSUE TITLE
Propozycje szablonu dla strony

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#6]
- Do 50 USD
- Statyczny HTML, mało js, css najlepiej w jakieś formie sass lub podobnej
- Strony to główna, na której będą wydarzenia, ogłoszenia, linki
- Żeby dało się zbudować strony i listy pod news, wydarzenia, jakiś blog post

**Comment by wolszakp** [comment]
Może coś stąd:
- https://themes.getbootstrap.com/
np:
https://themes.getbootstrap.com/preview/?theme_id=28779
Dawno nie robiłem nic front-u, więc nie bardzo wiem co teraz jest na topie.

**Comment by eklime** [comment]
@wolszakp mi jakoś "nie siada" ten szablon, no i przekracza założony budżet 👎

**Comment by kaluzaaa** [comment]
@eklime w sumie można do 50 USD zwiększyć, ale mi też nie siada

**Comment by wolszakp** [comment]
Luzik - rozumiem że to burza mózgów. Więc zgromadzimy ileś tam szablonów i wybierzemy najlepszy.

**Comment by aryll** [comment]
15$, widzę tam różne odsłony tego template'u ale nie do końca czuję czy ma szansę się sprawdzić
https://preview.themeforest.net/item/karma-responsive-clean-website-template/full_screen_preview/234990

**Comment by eklime** [comment]
> 15$, widzę tam różne odsłony tego template'u ale nie do końca czuję czy ma szansę się sprawdzić
> https://preview.themeforest.net/item/karma-responsive-clean-website-template/full_screen_preview/234990

Cena odzwierciedla jakość - na mobilku menu się wzięło i popsuło 🤣

**Comment by BartoszStartek** [comment]
A może coś w tym stylu:
1)https://preview.themeforest.net/item/gulluly-creative-digital-agency-multipurpose-html-template/full_screen_preview/20703913?_ga=2.71082515.2008524356.1597563521-555358776.1591807843
2)https://themes.getbootstrap.com/preview/?theme_id=4231
Albo coś z unify:
https://htmlstream.com/preview/unify-v2.6.3/index.html

**Comment by pchylak** [comment]
> A może coś w tym stylu:
> 1)https://preview.themeforest.net/item/gulluly-creative-digital-agency-multipurpose-html-template/full_screen_preview/20703913?_ga=2.71082515.2008524356.1597563521-555358776.1591807843
> 2)https://themes.getbootstrap.com/preview/?theme_id=4231
> Albo coś z unify:
> https://htmlstream.com/preview/unify-v2.6.3/index.html

Unify całkiem ciekawy i prosty jest ...

**Comment by mmisztal1980** [comment]
https://cleanui.cloud/ ?

**Comment by TomaszOledzki** [comment]
Postawcie coś na Jekyllu na szybko: https://jekyllrb.com oraz https://jekyllrb.com/docs/themes/.

Jest mega prosty w obsłudze, GitHub natywnie wspiera Jekylla - strona jest ładowana ze wskazanego repo/katalogu w repo ze wskazanego brancza.

**Comment by kaluzaaa** [comment]
@TomaszOledzki na szybko umiemy ;-) zobacz repo od mentoringu ;-) i założenia #8

**Comment by kaluzaaa** [comment]
[Taki kupiony](http://themeht.com/winck/index.html)

**Comment by mmisztal1980** [comment]
o fajne, już się theme'y do BS5 pojawiły?
