### ISSUE TITLE
Post o nowym wydarzeniu na stronie LinkedIn

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#7]
Przygotowanie jaki call wykonać w API i jak pozyskać token

**Comment by kamil-mrzyglod** [comment]
Wrzuć to na mnie, w wolnej chwili ogarnę "risercz".

**Comment by kamil-mrzyglod** [comment]
**TOKEN**:
Teoretycznie do użycia jest Authorization flow - https://docs.microsoft.com/en-us/linkedin/shared/authentication/client-credentials-flow?context=linkedin/context, jednak dokumentacja jednocześnie mówi:

> 2-legged OAuth authentication is not available for marketing APIs.

Więc prawdopodobnie(Share API to Marketing API) pozostaje Authorization Code Flow - https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin/context i postowanie wydarzeń w imieniu usera / organizacji. W ramach tego do ogarnięcia odświeżanie tokena dla aplikacji. 

**SHARE**:
Do użycia metoda _Share Content_ - https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/share-api#share-content

**TO DO**:

- organizacja w LinkedIn(https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations)
- aplikacja w LinkedIn(https://www.linkedin.com/developers/apps/new)
- uwierzytelnienie aplikacji w kontekście organizacji(czyli użytkownik z odpowiednimi uprawnieniami, które zostaną oddelegowane do aplikacji)

**Comment by eklime** [comment]
@kamil-mrzyglod https://www.linkedin.com/company/31415670/admin/ zapraszam - masz Admina.

**Comment by kamil-mrzyglod** [comment]
Appka stworzona(**MAUGP Share App**) i zweryfikowana. Można wokół niej robić dewelopment. @eklime & @kaluzaaa - macie admina na tej appce też.

**Comment by eklime** [comment]
@kamil-mrzyglod  przygotuj proszę HTTP request dla Logic App z wykorzystaniem tej apki

**Comment by kamil-mrzyglod** [comment]
@eklime - to chyba można w ogóle łatwiej zrobić(czyli bez appki):
![image](https://user-images.githubusercontent.com/11725731/90429734-8358c200-e0c6-11ea-8795-95fcae2f9be6.png)
Wystarczy wykombinować sensowny trigger. Mamy na to nawet docsy pod parametry: https://docs.microsoft.com/en-us/connectors/linkedinv2/#share-a-company-update-v2

**Comment by eklime** [comment]
O widzisz i taki risercz się ceni.
Ogólnie wrzucanie na Social Media ogarniemy zapewne jednym dużym LA, a triggerem będzie pewnie PR do GH z nowym wydarzeniem.
Można też pomyśleć o jakimś sensownym schedulerze
