### ISSUE TITLE
Po co azurecommunity.pl?

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#8]
- Hub o naszym community
- Jedno miejsce do zakładania wydarzeń przez każdego i uspójnienie grupy
- Miejsce na inne akcje (monitoring, konfy)
- Zrobienie wreszcie powiadomień mailowych dla wydarzeń bez problemu "sprzedaży maili"
- Automatyzacja i transparenty proces CFP dla wydarzeń

**To do**

- [ ]  Budowa strony na Github Pages- zaczynamy od  #6 
- [ ]  Budowa flow na PR wydarzenia i potem automatyzacji procesu. Proces będzie następujący: PR modyfikujący o nowe wydarzenie -> weryfikacja czy jest mail organizatora -> akceptacja PR -> RSS z yaml data -> Logic App na RSS, który wykona wszystkie reszty (z innych issues) - #1 #2 #3 #4 #5

**Inne pomysły?**

**Comment by RogalaPiotr** [comment]
nie kumam po co skorka wordpress jak ma byc github pages? chyba ze to osobny serwis?

**Comment by kaluzaaa** [comment]
@RogalaPiotr szablon html5 statyczny, tam nigdzie nie pisze o wordpress. Tak był właśnie na gh pages zrobiony mentoring -> https://github.com/azurecommunitypl/mentoring-2020

**Comment by RogalaPiotr** [comment]
@kaluzaaa w innym watku jest szablon do wordpress, czyli sa 2 rozne domeny i beda 2 rozne strony?

**Comment by kaluzaaa** [comment]
@RogalaPiotr jeśli ktoś zaproponował szablon od wordpress to zrobił to źle. 
#6 jasno mówi
```
- Do 50 USD
- Statyczny HTML, mało js, css najlepiej w jakieś formie sass lub podobnej
- Strony to główna, na której będą wydarzenia, ogłoszenia, linki
- Żeby dało się zbudować strony i listy pod news, wydarzenia, jakiś blog post
```

**Comment by mmisztal1980** [comment]
hugo?

**Comment by eklime** [comment]
> hugo?

Na GH Pages to bardziej Jekyll

**Comment by kaluzaaa** [comment]
Hugo też może być ok jak mamy gh actions. Sprawdzę jeszcze czy tak samo łatwo zrobić się myk z _data jak w jekyll
